<?php

namespace App\Notifications;

use App\Models\OfferLetter;
use App\Models\Tenant;
use App\Models\User;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * In-app + email notification to the agent's manager (or, when the agent has no
 * manager, the tenant's admins) that a new offer letter awaits approval.
 *
 * Deliberately synchronous (no ShouldQueue): the production server has no queue
 * worker, so the database channel must persist immediately.
 */
class OfferLetterApprovalRequired extends Notification
{
    public function __construct(
        protected OfferLetter $offerLetter,
        protected User $agent,
        protected Tenant $tenant,
    ) {}

    public function via(object $notifiable): array
    {
        return ['database', 'mail'];
    }

    public function toArray(object $notifiable): array
    {
        $deal = $this->offerLetter->deal;
        $leadName = $deal?->lead?->full_name ?? $this->offerLetter->lead?->full_name ?? '';

        return [
            'type' => 'offer_letter_approval',
            'icon' => 'file-check',
            'color' => 'yellow',
            'title' => __('Offer letter awaiting approval'),
            'body' => __(':agent generated offer :no for :lead — please approve it.', [
                'agent' => $this->agent->name,
                'no' => $this->offerLetter->offer_no,
                'lead' => $leadName ?: $this->offerLetter->deal?->title ?? '',
            ]),
            'url' => $deal ? url('/pipeline/'.$deal->id) : url('/pipeline'),
            'deal_id' => $deal?->id,
            'offer_letter_id' => $this->offerLetter->id,
        ];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $deal = $this->offerLetter->deal;
        $leadName = $deal?->lead?->full_name ?? $this->offerLetter->lead?->full_name ?? $deal?->title ?? '';

        return (new MailMessage)
            ->subject('[Keystone] Offer letter '.$this->offerLetter->offer_no.' awaits your approval')
            ->greeting("Hello {$notifiable->name},")
            ->line('An offer letter generated by '.$this->agent->name.' is waiting for your approval.')
            ->line('**Offer:** '.$this->offerLetter->offer_no)
            ->line('**Lead / Transaction:** '.$leadName)
            ->line('**Value:** '.\App\Helpers\TenantFormatHelper::currency($this->offerLetter->approved_amount))
            ->action('Review & Approve', $deal ? url('/pipeline/'.$deal->id) : url('/pipeline'))
            ->line('The deal cannot proceed until this offer letter is approved.');
    }
}
